### ISSUE TITLE
How to view in Wireshark?

### ISSUE THREAD

**Issue by Anonymous941** [PretendoNetwork/HokakuCTR#15]
I'm trying to reverse-engineer Pretendo, and can't view these on Wireshark.  All packets show up as `User encapsulation not handled: DLT=147, check your Preferences->Protocols->DLT_USER`, despite me installing the NEX plugin

**Comment by PabloMK7** [comment]
Reverse engeneering the reversed engeneered? Why not checking the nex go reimplementation instead? 🤔

Anyways: https://github.com/PretendoNetwork/nex-viewer

**Comment by Anonymous941** [comment]
ty, I'll try that

> Reverse engeneering the reversed engeneered? Why not checking the nex go reimplementation instead? 🤔

I'm trying to make a homebrew 3DS Mario Maker course downloader and it's not working, also I need the IP addresses which aren't in the source code...
