### ISSUE TITLE
Building latest version

### ISSUE THREAD

**Issue by Qiangong2** [PretendoNetwork/HokakuCTR#2]
I tried to build v1.0.1 from source, but I get stuck on:
```
/home/qg2/hokakuctr/Includes/OSDManager.hpp:5:10: fatal error: CTRPluginFramework.hpp: No such file or directory
    5 | #include "CTRPluginFramework.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [OSDManager.o] Error 1
make: *** [Build] Error 2
```
Do I need to install additional tools beyond devkitpro?

**Comment by PabloMK7** [comment]
Yes, you need the latest version of CTRPluginFramework and 3GX tool. You can use this docker image to have a working environment: pablomk7/libctrpf:0.7.2

**Comment by Qiangong2** [comment]
That did it, thanks
