### ISSUE TITLE
ZL, ZR, and C-Stick do not work on N3DS

### ISSUE THREAD

**Issue by N7Kopper** [PretendoNetwork/HokakuCTR#7]
It is as it sounds: when using HokakuCTR, the N3DS' built-in Circle Pad Pro features don't work. This is true both when the system is emulating a CPP (tested on Smash 3DS EUR: despite not loading the drivers on an O3DS, the N3DS is still emulating the CPP) and when the game natively supports N3DS features (tested on Tri-Force Heroes EUR).

The buttons and stick do work on the Home Menu, so it's not a hardware issue.

**Comment by PabloMK7** [comment]
This is a known issue with plugins and Luma3DS, not related to Hokaku. To get around it for now enable input redirection from the Rosalina menu
