### ISSUE TITLE
HarmoKnight/Nintendo Video titles crashing with HokakuCTR enabled

### ISSUE THREAD

**Issue by einso** [PretendoNetwork/HokakuCTR#8]
I've encountered an issue where the game HarmoKnight, as well as any official Nintendo Video title from the eShop, will crash the console, requiring a hard reboot. 
This issue appears in v1.0.1, as well as v1.0.2. The issue stops occurring once Luma plugin loader is disabled through Rosalina, or if the plugin is no longer present.

This is not necessarily an issue per se, as neither of these titles have network functionality, but it is a nuisance.

I have attached crash dump logs from Luma for both cases for referencing.

[Nintendo Video - crash_dump_00000000.dmp](https://github.com/PretendoNetwork/HokakuCTR/files/13251885/Nintendo.Video.-.crash_dump_00000000.dmp)
[HarmoKnight - crash_dump_00000001.dmp](https://github.com/PretendoNetwork/HokakuCTR/files/13251886/HarmoKnight.-.crash_dump_00000001.dmp)

**Comment by PabloMK7** [comment]
Hello, this is an issue with CTRPF, not HokakuCTR. Will close the issue. Thanks for the crash dumps.
